##########################
####### TEMPLATES #########
##########################
srcFolder: &srcFolder
  includeFilesPattern:
    src/: php

testsFolder: &testsFolder
  includeFilesPattern:
    tests/: php

phpstan: &phpstan
  cmd:
    - "{php_cmd}"
    - "-dmemory_limit=-1"
    - "./vendor/bin/phpstan"
    - analyse
    - "-cphpstan.neon"
  includeFiles: true
  reverseOutput: true

phpcs: &phpcs
  error_msg: Php code sniffer failed
  timeout: 180
  cmd:
    - "{composer_cmd}"
    - phpcs
  includeFiles: true

##########################
####### END TEMPLATES #####
##########################

name: Pre-commit hook
description: Pre-commit hook parallel execution
globalEnvFile: null
globalEnv:
  XDEBUG_MODE: off
commands:
  ##########################
  ####### PHPSTAN BEGIN #####
  ##########################
  phpstan-src:
    <<: *phpstan
    <<: *srcFolder
    name: Phpstan src
    description: Static analyzer for source

  phpstan-tests:
    <<: *phpstan
    <<: *testsFolder
    name: Phpstan tests
    description: Static Analyzer tests folder
  ##########################
  ####### PHPSTAN END #######
  ##########################

  ##########################
  ####### PHPCS BEGIN ########
  ##########################
  phpcs-src:
    <<: *phpcs
    <<: *srcFolder
    name: Phpcs src
    description: Run php code sniffer for src

  phpcs-tests:
    <<: *phpcs
    <<: *testsFolder
    name: Phpcs tests
    description: Run php code sniffer for tests
  ##########################
  ####### PHPCS END #########
  ##########################

  ##########################
####### TESTS BEGIN ########
##########################
  tests:
    name: Tests
    description: Run tests
    cmd:
      - "{php_cmd}"
      - "-dmemory_limit=-1"
      - "./vendor/bin/phpunit"
    includeFiles: true
    forceDisableAttachArgs: true
    includeFilesPattern:
      tests: php
      src: php

##########################
####### TESTS END #########
##########################
